// Auto-generated by @tanstack/router — do not edit manually
// Run "pnpm dev" to regenerate this file
import { Route as rootRoute } from './routes/__root.js'
import { Route as IndexRoute } from './routes/index.js'
import { Route as LoginRoute } from './routes/login.js'
import { Route as DashboardRoute } from './routes/dashboard.js'

const routeTree = rootRoute.addChildren([IndexRoute, LoginRoute, DashboardRoute])

export { routeTree }
